name: analysis
channels: 
 # running defaults ahead of forge will likely get you mkl (on windows)
 - defaults
 - conda-forge
dependencies:
 - python
 - pip
 - notebook
 - jupyterlab
 - numpy
#  - numexpr # depend MKL install
#  - "libblas=*=*mkl" # for intel MKL numpy
 - xarray
 - pandas
 - matplotlib
 - seaborn
 - scikit-learn
 - scipy
 - statsmodels
 - matplotlib
 - h5py
 - scikit-image
 - imageio
 - imageio-ffmpeg
 - dask # optional
 - numba # optional
 - cython # optional, for OASIS
 - pip:
   - pytest
   - scanimage-tiff-reader
   - tqdm
   - tifffile
  #  - jax[cpu] # will not work in windows
  #  - git+https://github.com/j-friedrich/OASIS # might not build in windows